ARG NODE_TAG=lts-slim

FROM node:${NODE_TAG}

WORKDIR /usr/client

COPY package*.json ./

# Install Dependencies - Only if package.json changes (cache improvements to avoid re-installing dependencies every time)
RUN npm install

COPY ./ ./

EXPOSE 3000

CMD ["npm", "run", "dev"]