version: '3.8'
services:
  rest-service:
    build:
      context: ./spendaro/api
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./spendaro/api:/usr/api
    ports:
      - "8000:8000"
  client-service:
    build:
      context: ./spendaro/client
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./spendaro/client:/usr/app
      - /usr/app/node_modules
    environment:
      - VITE_PROXY_URL=http://rest-service:8000
      - VITE_APP_PORT=5173
    ports:
      - "5173:5173"
