version: '3.3'
services:
  rest-service:
    build: 
      context: ./spendaro/api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - ./spendaro/api/.env.local
  client-service:
    build: 
      context: ./spendaro/client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - ./spendaro/api/.env.local
